export const traducoes = {
  en: {
    title: "Investment Calculator",
    subtitle: "Plan your financial future with our easy-to-use calculator",
    formTitle: "Investment Parameters",
    initialInvestment: "Initial Investment",
    monthlyContribution: "Monthly Contribution",
    investmentPeriod: "Investment Period (Years)",
    annualInterestRate: "Expected Annual Interest Rate",
    required: "required",
    usd: "USD",
    years: "years",
    percent: "%",
    initialInvestmentHelp: "Your starting investment amount",
    monthlyContributionHelp: "Amount you'll contribute each month",
    investmentPeriodHelp: "How long you plan to invest (1-50 years)",
    interestRateHelp: "Expected annual return rate (0-20%)",
    summary: "Summary",
    initialInvestmentLabel: "Initial Investment:",
    monthlyContributionLabel: "Monthly Contribution:",
    investmentPeriodLabel: "Investment Period:",
    annualInterestRateLabel: "Annual Interest Rate:",
    resultsTitle: "Investment Results",
    totalInvested: "Total Invested",
    totalInterestEarned: "Total Interest Earned",
    finalAmount: "Final Amount",
    ofFinalAmount: "of final amount",
    totalAfterGrowth: "Total after {growth}% growth",
    growthRate: "Growth Rate:",
    interestRatio: "Interest Ratio:",
    averageAnnualReturn: "Average Annual Return:",
    chartTitle: "Investment Growth Over Time",
    chartDescription: "This chart shows how your investment grows over time, including your contributions and the compound interest earned. The lines represent:",
    totalInvestedDescription: "Your cumulative contributions",
    interestEarnedDescription: "Compound interest generated",
    finalAmountDescription: "Total value of your investment",
    footer: "© 2024 Investment Calculator. Plan wisely, invest smartly.",
    language: "Language",
    english: "English",
    portuguese: "Português"
  },
  
  pt: {
    title: "Calculadora de Investimentos",
    subtitle: "Planeje seu futuro financeiro com nossa calculadora fácil de usar",
    formTitle: "Parâmetros do Investimento",
    initialInvestment: "Investimento Inicial",
    monthlyContribution: "Contribuição Mensal",
    investmentPeriod: "Período de Investimento (Anos)",
    annualInterestRate: "Taxa de Juros Anual Esperada",
    required: "obrigatório",
    usd: "BRL",
    years: "anos",
    percent: "%",
    initialInvestmentHelp: "Seu valor inicial de investimento",
    monthlyContributionHelp: "Valor que você contribuirá mensalmente",
    investmentPeriodHelp: "Por quanto tempo você planeja investir (1-50 anos)",
    interestRateHelp: "Taxa de retorno anual esperada (0-20%)",
    summary: "Resumo",
    initialInvestmentLabel: "Investimento Inicial:",
    monthlyContributionLabel: "Contribuição Mensal:",
    investmentPeriodLabel: "Período de Investimento:",
    annualInterestRateLabel: "Taxa de Juros Anual:",
    resultsTitle: "Resultados do Investimento",
    totalInvested: "Total Investido",
    totalInterestEarned: "Juros Totais Ganhos",
    finalAmount: "Valor Final",
    ofFinalAmount: "do valor final",
    totalAfterGrowth: "Total após {growth}% de crescimento",
    growthRate: "Taxa de Crescimento:",
    interestRatio: "Razão de Juros:",
    averageAnnualReturn: "Retorno Médio Anual:",
    chartTitle: "Crescimento do Investimento ao Longo do Tempo",
    chartDescription: "Este gráfico mostra como seu investimento cresce ao longo do tempo, incluindo suas contribuições e os juros compostos ganhos. As linhas representam:",
    totalInvestedDescription: "Suas contribuições cumulativas",
    interestEarnedDescription: "Juros compostos gerados",
    finalAmountDescription: "Valor total do seu investimento",
    footer: "© 2024 Calculadora de Investimentos. Planeje com sabedoria, invista com inteligência.",
    language: "Idioma",
    english: "English",
    portuguese: "Português"
  }
}; 